version: '3.8'

services:
  web:
    build: .
    command: gunicorn carelink_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[your-ec2-ip]
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"

volumes:
  static_volume:
  media_volume: 