# Generated by Django 5.1.6 on 2025-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0002_medication_created_at_medication_next_refill_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthtip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='healthtip',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General Health'), ('NUTRITION', 'Nutrition'), ('FITNESS', 'Fitness'), ('MENTAL', 'Mental Health'), ('ELDERLY', 'Elderly Care'), ('PEDIATRIC', 'Pediatric Care'), ('CHRONIC', 'Chronic Disease Management'), ('PREVENTIVE', 'Preventive Care')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='healthtip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='health_tips/'),
        ),
        migrations.AddField(
            model_name='healthtip',
            name='source',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
