# Generated by Django 5.1.6 on 2025-03-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0003_alter_healthtip_options_healthtip_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carerequest',
            name='patient_age',
        ),
    ]
