# Generated by Django 5.1.6 on 2025-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0004_remove_carerequest_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequest',
            name='service_type',
            field=models.CharField(blank=True, choices=[('HOME_CARE', 'Home Care'), ('MEDICAL_ASSISTANCE', 'Medical Assistance'), ('RESPITE_CARE', 'Respite Care'), ('SPECIALIZED_CARE', 'Specialized Care')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carerequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('NEW_PATIENT', 'New Patient'), ('SERVICE', 'Service')], max_length=20, null=True),
        ),
    ]
