# Generated by Django 5.1.6 on 2025-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0005_carerequest_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthanalysis',
            name='avg_oxygen_level',
            field=models.IntegerField(null=True),
        ),
    ]
