# Generated by Django 5.1.6 on 2025-03-02 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0006_healthanalysis_avg_oxygen_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(35.0, message='Temperature cannot be below 35.0°C'), django.core.validators.MaxValueValidator(42.0, message='Temperature cannot exceed 42.0°C')]),
        ),
    ]
