# Generated by Django 5.1.6 on 2025-03-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0008_alter_healthlog_temperature_healthinsight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlinsight',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mlprediction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mlrecommendation',
            name='user',
        ),
        migrations.AddField(
            model_name='mlinsight',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_insights', to='carelink.patient'),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='carelink.patient'),
        ),
        migrations.AddField(
            model_name='mlrecommendation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_recommendations', to='carelink.patient'),
        ),
    ]
