# Generated by Django 5.1.7 on 2025-03-15 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0011_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='exercise_type',
            field=models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('yoga', 'Yoga'), ('strength', 'Strength Training'), ('other', 'Other')], default='walking', max_length=50),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
