# Generated by Django 5.1.7 on 2025-03-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0012_remove_exerciselog_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], default='DAILY', max_length=20)),
                ('reminder_time', models.TimeField()),
                ('days_of_week', models.CharField(blank=True, help_text='Comma-separated days for weekly reminders', max_length=100)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly reminders', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('next_reminder', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='carelink.medication')),
            ],
            options={
                'ordering': ['next_reminder'],
            },
        ),
    ]
