# Generated by Django 5.1.7 on 2025-03-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0016_taskattachment_taskcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='carelink_ta_due_dat_d5a10d_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='carelink_ta_patient_20a6f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='carelink_ta_caregiv_bd105f_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_recurrence',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder_before',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder_enabled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_caregiver',
            field=models.OneToOneField(limit_choices_to={'user_type': 'CAREGIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('MEDICATION', 'Medication'), ('HEALTH_CHECK', 'Health Check'), ('APPOINTMENT', 'Appointment'), ('EXERCISE', 'Exercise'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
