# Generated by Django 5.1.7 on 2025-03-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0017_remove_taskattachment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_requests', to='carelink.patient'),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carerequest',
            name='patient_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carerequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
