# Generated by Django 5.1.7 on 2025-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0018_carerequest_notes_carerequest_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='service_type',
            field=models.CharField(blank=True, choices=[('HOME_CARE', 'Home Care'), ('MEDICAL_ASSISTANCE', 'Medical Assistance'), ('RESPITE_CARE', 'Respite Care'), ('SPECIALIZED_CARE', 'Specialized Care')], max_length=20, null=True),
        ),
    ]
