# Generated by Django 5.1.7 on 2025-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0019_patient_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='service_type',
        ),
        migrations.AddField(
            model_name='healthlog',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ATTENTION', 'Needs Attention'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
    ]
