# Generated by Django 5.1.7 on 2025-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0020_remove_patient_service_type_healthlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthlog',
            name='status',
        ),
        migrations.AddField(
            model_name='healthlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='title',
            field=models.CharField(default='Health Check', max_length=200),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
