# Generated by Django 5.1.7 on 2025-03-16 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0021_remove_healthlog_status_healthlog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='healthlog',
            name='title',
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='notes',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('GENERAL', 'General Physician'), ('CARDIO', 'Cardiologist'), ('NEURO', 'Neurologist'), ('ORTHO', 'Orthopedic'), ('PSYCH', 'Psychiatrist'), ('OTHER', 'Other Specialist')], max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('availability_status', models.BooleanField(default=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emergency_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PRIMARY', 'Primary Doctor'), ('SECONDARY', 'Secondary Doctor'), ('SPECIALIST', 'Specialist'), ('EMERGENCY', 'Emergency Contact')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_patients', to='carelink.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='carelink.patient')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('REPORT', 'Medical Report'), ('PRESCRIPTION', 'Prescription'), ('TEST', 'Test Result'), ('OTHER', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to='medical_files/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='carelink.patient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=20)),
                ('is_emergency', models.BooleanField(default=False)),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='carelink.doctor')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='carelink.patient')),
            ],
        ),
    ]
