# Generated by Django 5.1.7 on 2025-03-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carelink', '0022_remove_healthlog_description_remove_healthlog_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocall',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='sharedfile',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='sharedfile',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='patient',
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='status',
            field=models.CharField(choices=[('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('RESCHEDULED', 'Rescheduled')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='SharedFile',
        ),
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
