name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to project directory
          cd ~/carelink
          
          # Pull latest changes
          git pull origin main
          
          # Build and restart containers
          docker-compose down
          docker-compose build
          docker-compose up -d
          
          # Clean up old images
          docker image prune -f 